(define (make-point x y)
  (cons x y))
(define (x-point p)
  (car p))
(define (y-point p)
  (cdr p))
(define (print-point p)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")")
  (newline))
(define (make-segment start end)
  (cons start end))
(define (start-segment s)
  (car s))
(define (end-segment s)
  (cdr s))
(define (midpoint-segment s)
  (let ((start (/ (+ (x-point (start-segment s)) (x-point (end-segment s))) 2.0))
        (end (/ (+ (y-point (start-segment s)) (y-point (end-segment s))) 2.0)))
    (make-point start end)))
(define p1 (make-point 1 3))
(define p2 (make-point 4 3))

(define s (make-segment p1 p2))
(print-point (midpoint-segment s))