;(define (cons x y)
;  (define (temp i)
;    (cond ((= i 0) x)
;          ((= i 1) y)))
;  temp)
;(define (car z)
;  (z 0))
;(define (cdr z)
;  (z 1))
(define (cons x y)
  (lambda (m) (m x y)))
(define (car z)
  (z (lambda (p q) p)))
(define (cdr z)
  (z (lambda (p q) q)))
(cdr (cons 1 2))
