#lang racket
(define (make-from-mag-ang x y)
  (define (dispatch op)
    (cond ((eq? op 'real-part) (* x (cos y)))
          ((eq? op 'imag-part) (* x (sin y)))
          ((eq? op 'magnitude) x)
          ((eq? op 'angle) y)))
  dispatch)
(define (apply-generic op arg)
  (arg op))
(define c (make-from-mag-ang 3 4))
(apply-generic 'real-part c)
(apply-generic 'imag-part c)
(apply-generic 'magnitude c)
(apply-generic 'angle c)
