#lang racket
;a
(define (make-mobile left right)
  (list left right))
(define (make-branch length structure)
  (list length structure))
(define (left-branch mobile)
  (car mobile))
(define (right-branch mobile)
  (cadr mobile))
(define (branch-length branch)
  (car branch))
(define (branch-structure branch)
  (cadr branch))
;b
(define (branch-weight branch)
  (if (pair? (branch-structure branch))
      (total-weight (branch-structure branch))
      (branch-structure branch)))

(define (total-weight mobile)
  (+ (branch-weight (left-branch mobile))
     (branch-weight (right-branch mobile))))

(define mobile (make-mobile (make-branch 10 20)
                            (make-branch 10 25)))
(define mobile1 (make-mobile (make-branch 10 mobile)
                             (make-branch 10 20)))
(total-weight mobile1)

;c
(define (branch-torque branch)
  (* (branch-length branch)
     (branch-weight branch)))

(define (hangs-mobile? branch)
  (pair? (branch-structure branch)))

(define (mobile-balance? mobile)
  (let ((left (left-branch mobile))
        (right (right-branch mobile)))
    (and (= (branch-torque left)
            (branch-torque right))
         (if (hangs-mobile? left)
             (mobile-balance? (branch-structure left))
             true)
         (if (hangs-mobile? right)
             (mobile-balance? (branch-structure right))
             true))))

(define balance-mobile (make-mobile (make-branch 10 10)
                                    (make-branch 10 10)))
(define balance-mobile1 (make-mobile (make-branch 0 0)
                                     (make-branch 10 10)))
(define mobile-with-sub-mobile (make-mobile (make-branch 10 balance-mobile)
                                            (make-branch 10 balance-mobile)))
(mobile-balance? mobile-with-sub-mobile)

;d
(define (make-mobile1 left right)
  (cons left right))
(define (make-branch1 length structure)
  (cons length structure))
(define (left-branch1 mobile)
  (car mobile))
(define (right-branch1 mobile)
  (cdr mobile))
(define (branch-length1 branch)
  (car branch))
(define (branch-structure1 branch)
  (cdr branch))