#lang racket
(define (call-the-cops)
  "cops!")
(define (make-account balance password)
  (let ((try-times 0))
    (define (withdraw amount pwd)
      (if (equal? pwd password)
          (if (>= balance amount)
              (begin
                (set! balance (- balance amount))
                balance)
              "error!")
          (if (>= try-times 7)
              (call-the-cops)
              (begin
                (set! try-times (+ try-times 1))
                "error!"))))
    withdraw))

(define A (make-account 100 'guo))
(A 10 'g)
(A 10 'g)
(A 10 'g)
(A 10 'g)
(A 10 'g)
(A 10 'g)
(A 10 'g)
(A 10 'g)
(A 10 'g)
