(define (square x) (* x x))
(define (even? x)
  (= (remainder x 2) 0))
(define (fast-expt b n a)
  (cond ((= n 0) a)
        ((even? n) (fast-expt (square b) (/ n 2) a))
        (else (fast-expt b (- n 1) (* a b)))))
(define (expt b n)
  (fast-expt b n 1))
(expt 4 3)
